

@protocol = http
@hostname = localhost
@port = 5000
@host = {{protocol}}://{{hostname}}:{{port}}

@webhooks_api = {{host}}/webhooks
@events_api = {{host}}/events

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ

@contentType = application/json


###
# @name register_webhook
###
curl --request POST \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}' \
  --header 'content-type: {{contentType}}' \
  --data '{
    "url": "https://en9bayo995ajl.x.pipedream.net",
    "trigger": "something_happened",
    "content": "123.456.789",
    "additionalHeaders": {}}'


###
# @name get_all_registered_webhooks
curl --request GET \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}'

###
# @name get_registered_webhook
curl --request GET \
  --url {{webhooks_api}}/17578ad8-2bbc-4595-b641-03f54922f0ed \
  --header 'authorization: {{authToken}}'

###
# @name trigger_webhooks
curl --request POST \
  --url {{events_api}} \
  --header 'authorization: {{authToken}}' \
  --header 'content-type: {{contentType}}' \
  --data '{"eventName": "something_happened"}'




### Used https://requestbin.com to test webhooks

###
curl -d '{ "name": "Darth Vader" }' \
  -H "Content-Type: application/json" \
  https://enpo0mqeo4e.x.pipedream.net/

###
https://requestbin.com/r/en9bayo995ajl/29UByXvXsakhUOHQ1DRuknkAcFl
https://requestbin.com/r/enpo0mqeo4e/29UByXnD84uVwEK0ZuUHFgcb8pn

https://en9bayo995ajl.x.pipedream.net

