

@protocol = http
@hostname = localhost
@port = 5000
@host = {{protocol}}://{{hostname}}:{{port}}

@webhooks_api = {{host}}/webhooks

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ

@contentType = application/json


###
# @name register_webhook
###
curl --request POST \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}' \
  --header 'content-type: {{contentType}}' \
  --data '{
    "url": "https://docs.webhook.site/",
    "trigger": "price_added",
    "secret": "123.456.789",
    "additional_headers": {}}'


###
# @name get_all_registered_webhooks
curl --request GET \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}'

###
# @name get_registered_webhook
curl --request GET \
  --url {{webhooks_api}}/28f091d5-969f-4b5a-a7c2-cfd527a0c837 \
  --header 'authorization: {{authToken}}'

###
# @name unregister_webhook



# return paged data back, list of dto's
# {}
#
#
###


