

@protocol = http
@hostname = localhost
@port = 5000
@host = {{protocol}}://{{hostname}}:{{port}}

@webhooks_api = {{host}}/webhooks
@events_api = {{host}}/events

@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ

@contentType = application/json


###
# @name register_webhook
###
curl --request POST \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}' \
  --header 'content-type: {{contentType}}' \
  --data '{
    "url": "https://webhook.site/token/c874ddf0-7592-49c4-9a8f-e7dbb6319261/",
    "trigger": "something_happened",
    "content": "123.456.789",
    "additionalHeaders": {}}'


###
# @name get_all_registered_webhooks
curl --request GET \
  --url {{webhooks_api}} \
  --header 'authorization: {{authToken}}'

###
# @name get_registered_webhook
curl --request GET \
  --url {{webhooks_api}}/28f091d5-969f-4b5a-a7c2-cfd527a0c837 \
  --header 'authorization: {{authToken}}'

###
# @name trigger_webhooks
curl --request POST \
  --url {{events_api}} \
  --header 'authorization: {{authToken}}' \
  --header 'content-type: {{contentType}}' \
  --data '{"eventName": "something_happened"}'


###
# @name get_requests_to_webhook_test_url
# "uuid": "c874ddf0-7592-49c4-9a8f-e7dbb6319261",
curl --request GET \
  --url https://webhook.site/token/c874ddf0-7592-49c4-9a8f-e7dbb6319261/requests


###
# @name create_webhook_test_url
curl --request POST --url https://webhook.site/token

